# Infos personnelles
title: "Perceval Beja-Battais"
description: "PhD Student in Applied Mathematics & Machine Learning | Centre Borelli - ENS Paris-Saclay"
url: "https://pbb2.github.io"

# Auteur
author:
  name: "Perceval Beja-Battais"
  position: "PhD Student"
  affiliation: "ENS Paris-Saclay"
  email: "perceval.beja-battais@ens-paris-saclay.fr"
  github: 
  google_scholar: "https://scholar.google.com/citations?user=Qt7AfjsAAAAJ&hl=fr"       # ID Scholar optionnel

# Photo de profil
profile:
  image: prof_pic.jpg        # dans assets/img/

header_pages:
  - _pages/about.md
  - _pages/publications.md

# Activer/désactiver des sections
news: true
selected_papers: true
social: true
